import{a as m,S as f,i as a}from"./assets/vendor-ee72e1a4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function n(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(r){if(r.ep)return;r.ep=!0;const s=n(r);fetch(r.href,s)}})();const g="https://pixabay.com/api/",p="43896740-362a21d10e9d41ec216c05f15",h=async(o,t)=>(await m.get(g,{params:{key:p,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data,y=new f(".gallery a"),u=(o,t)=>{const n=o.map(i=>`<li class="photo-card">
              <a class="gallery__item" href="${i.largeImageURL}">
                <img class="gallery__image" src="${i.webformatURL}" alt="${i.tags}" loading="lazy" />
              </a>
              <div class="info">
                <p class="info-item"><b>Likes</b> ${i.likes}</p>
                <p class="info-item"><b>Views</b> ${i.views}</p>
                <p class="info-item"><b>Comments</b> ${i.comments}</p>
                <p class="info-item"><b>Downloads</b> ${i.downloads}</p>
              </div>
            </li>`).join("");t.insertAdjacentHTML("beforeend",n),y.refresh()},e={form:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreButton:document.querySelector(".load-more")};let l="",c=1;e.form.addEventListener("submit",L);e.loadMoreButton.addEventListener("click",b);async function L(o){if(o.preventDefault(),l=o.target.elements.search.value.trim(),c=1,l===""){a.error({title:"⨻",message:"Please enter text to find something!",position:"topRight"});return}e.loader.classList.remove("is-hidden"),e.gallery.innerHTML="",e.loadMoreButton.classList.add("is-hidden");try{const t=await h(l,c);if(t.hits.length===0){a.error({title:"⨻",message:"Sorry, there are no images your search query!",position:"topRight"});return}u(t.hits,e.gallery),e.loader.classList.add("is-hidden"),t.hits.length>=15&&e.loadMoreButton.classList.remove("is-hidden")}catch(t){console.error("Error fetching images:",t),a.error({title:"⨻",message:"An error occurred while fetching images.",position:"topRight"}),e.loader.classList.add("is-hidden")}}async function b(){c+=1,e.loader.classList.remove("is-hidden"),e.loadMoreButton.classList.add("is-hidden");try{const o=await h(l,c);u(o.hits,e.gallery),e.loader.classList.add("is-hidden"),o.hits.length<15?(a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),e.loadMoreButton.classList.add("is-hidden")):e.loadMoreButton.classList.remove("is-hidden");const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch(o){console.error("Error fetching images:",o),a.error({title:"⨻",message:"An error occurred while fetching images.",position:"topRight"}),e.loader.classList.add("is-hidden")}}
//# sourceMappingURL=commonHelpers.js.map
